name: sample-nodejsapp
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eighty8io/notifications-service
  name: sample-nodejs-do
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eighty8io/sample-nodejs
  name: sample-nodejs-eighty8io
