name: sample-nodejs
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-nodejs
  name: sample-nodejs
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: eighty8io/sample-nodejs
  name: sample-nodejs
